try {
    console.log(naoExisto);
} catch(erro) {
    console.log('naoExisto n√£o existe.');
    console.log(erro);
}